name: marksman
summary: LSP server for Markdown
description: |
  Write Markdown with code assist and intelligence in the comfort of your
  favourite editor.
icon: assets/readme/logo.png
license: MIT
issues: https://github.com/artempyanykh/marksman/issues
source-code: https://github.com/artempyanykh/marksman
base: core22
adopt-info: marksman
grade: stable
confinement: strict
architectures:
  - build-on: amd64
  - build-on: arm64

apps:
  marksman:
    command: ./marksman
    plugs:
      - home
      - network-bind

parts:
  marksman:
    plugin: nil
    build-packages:
      - make
      - wget
      - git
      - libicu70
    stage-packages:
      - libicu70
    source: .
    override-pull: |
      craftctl default
      wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh
      chmod +x ./dotnet-install.sh
      ./dotnet-install.sh --channel 9.0
    override-build: |
      craftctl default
      craftctl set version="$(git describe --tags)"
      export DOTNET_ROOT=$HOME/.dotnet
      export PATH=$PATH:$HOME/.dotnet:$HOME/.dotnet/tools
      make publishTo DEST=$SNAPCRAFT_PART_INSTALL
      chmod 0755 $SNAPCRAFT_PART_INSTALL/marksman
