name: marksman
summary: LSP server for Markdown
description: |
  Write Markdown with code assist and intelligence in the comfort of your
  favourite editor.
icon: assets/readme/logo.png
license: MIT
issues: https://github.com/artempyanykh/marksman/issues
source-code: https://github.com/artempyanykh/marksman
base: core22
adopt-info: marksman
grade: stable
confinement: strict
architectures:
  - build-on: amd64
  - build-on: arm64

apps:
  marksman:
    command: ./marksman
    plugs:
      - home
      - network-bind

parts:
  marksman:
    plugin: dotnet
    build-packages:
      - dotnet-sdk-7.0
      - make
    stage-packages:
      - libicu70
    source: .
    override-build: |
      craftctl default
      craftctl set version="$(git describe --tags)"
      make publishTo DEST=$SNAPCRAFT_PART_INSTALL
      chmod 0755 $SNAPCRAFT_PART_INSTALL/marksman
